import {supabase,isSupabaseConfigured} from "./supabase/client";
import type {CommunityComment,CommunityPost} from "./types";
import {communityPosts} from "./mockCommunityData";
export const demoMode=!isSupabaseConfigured;
function mapPost(p:any):CommunityPost{return {id:p.id,displayName:p.display_name,ageRange:p.age_range||"",topic:p.topic_slug,title:p.title,body:p.body,createdAt:p.created_at?new Date(p.created_at).toLocaleString("ja-JP"):"いま",likes:p.community_reactions?.length||0,comments:(p.community_comments||[]).filter((c:any)=>c.status==="published").map((c:any)=>({id:c.id,displayName:c.display_name,body:c.body,createdAt:new Date(c.created_at).toLocaleString("ja-JP")}))}}
export async function listPosts(topic?:string){if(!supabase)return topic?communityPosts.filter(p=>p.topic===topic):communityPosts;let q=supabase.from("community_posts").select("*, community_comments(*), community_reactions(*)").eq("status","published").order("created_at",{ascending:false});if(topic)q=q.eq("topic_slug",topic);const {data,error}=await q;if(error)throw error;return (data||[]).map(mapPost)}
export async function createPost(input:{displayName:string;ageRange:string;topic:string;title:string;body:string;lineUserId?:string}){if(!supabase)return {id:`demo-${Date.now()}`, ...input,createdAt:"いま",likes:0,comments:[]} as CommunityPost;let userId:string|undefined;if(input.lineUserId){const {data:user,error:userError}=await supabase.from("users").upsert({line_user_id:input.lineUserId,display_name:input.displayName,age_range:input.ageRange},{onConflict:"line_user_id"}).select("id").single();if(userError)throw userError;userId=user.id}const {data,error}=await supabase.from("community_posts").insert({user_id:userId||null,display_name:input.displayName,age_range:input.ageRange,topic_slug:input.topic,title:input.title,body:input.body}).select("*, community_comments(*), community_reactions(*)").single();if(error)throw error;return mapPost(data)}
export async function addComment(input:{postId:string;displayName:string;body:string}){if(!supabase)return {id:`demo-comment-${Date.now()}`,...input,createdAt:"いま"} as CommunityComment;const {data,error}=await supabase.from("community_comments").insert({post_id:input.postId,display_name:input.displayName,body:input.body}).select().single();if(error)throw error;return {id:data.id,displayName:data.display_name,body:data.body,createdAt:new Date(data.created_at).toLocaleString("ja-JP")}}
export async function addReaction(postId:string){if(!supabase)return {ok:true};const {error}=await supabase.from("community_reactions").insert({post_id:postId,reaction_type:"like"});if(error)throw error;return {ok:true}}
export async function report(input:{postId?:string;commentId?:string;reason:string}){if(!supabase)return {ok:true};const {error}=await supabase.from("community_reports").insert({post_id:input.postId,comment_id:input.commentId,reason:input.reason});if(error)throw error;return {ok:true}}
